source 'https://rubygems.org'
ruby File.read(File.dirname(__FILE__)+'/.ruby-version').strip

gem 'async-io'
gem 'json'
gem 'falcon'

# gem 'rack', '~> 2.2.8'
# gem 'rackup', '~> 2.1'
gem 'rack'
gem 'rackup'

gem 'sinatra'
gem 'sinatra-contrib'
# gem 'sinatra-reloader'
gem 'slim'
gem 'rack-sassc'
gem 'rest-client'


gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'

group :development do
  gem 'rubocop'
end
